name: Selenium Grid Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: ['chrome', 'edge']
        instance: [1, 2, 3, 4, 5]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Start Selenium Grid Tests
      run: ./gradlew test --tests *YourTestClass* -Dbrowser=${{ matrix.browser }}
